name: ${COMPOSE_PROJECT_NAME:-stack-orchestra}

networks:
  stack-orchestra:
    driver: bridge

volumes:
  elasticsearch-data:
  neo4j-data:
  neo4j-logs:
  postgres-data:
  mysql-data:
  arangodb-data:
  mongodb-data:
  prometheus-data:
  grafana-data:
  scylla-data:
  qdrant-data:
  milvus-data:
  etcd-data:
  minio-data:
  dynamodb-data:
  rabbitmq-data:
  consul-data:

